version: "3.8"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wp-net

  redis:
    image: redis:alpine
    networks:
      - wp-net

  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
      - redis
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WP_REDIS_HOST: redis
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    networks:
      - wp-net

  reverse-proxy:
    image: nginx:alpine
    depends_on:
      - wordpress
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - wp-net

networks:
  wp-net:
    driver: bridge

volumes:
  mysql_data:
